### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xalabax** [Milad-Akarie/pretty_dio_logger#4]
020-01-09 21:27:36.990 I: ╔╣ Response ║ POST ║ Status: 200 OK
2020-01-09 21:27:36.990 I: ║  https://-------------------------/Feed/SavePost
2020-01-09 21:27:36.990 I: ╚══════════════════════════════════════════════════════════════════════════════════════════
2020-01-09 21:27:36.990 I: ╔ Body
2020-01-09 21:27:36.990 I: ║
2020-01-09 21:27:36.997 I: @@@ onButtonShareClick error=DioError [DioErrorType.DEFAULT]: type 'int' is not a subtype of type 'String'
2020-01-09 21:27:36.997 I: #0      PrettyDioLogger._printResponse (package:pretty_dio_logger/pretty_dio_logger.dart:145:30)
2020-01-09 21:27:36.997 I: #1      PrettyDioLogger.onResponse (package:pretty_dio_logger/pretty_dio_logger.dart:121:7)
2020-01-09 21:27:36.997 I: #2      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:828:37)
2020-01-09 21:27:36.997 I: #3      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1099:22)
2020-01-09 21:27:36.997 I: #4      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:825:22)
2020-01-09 21:27:36.998 I: #5      new Future.<anonymous closure> (dart:async/future.dart:176:37)
2020-01-09 21:27:36.998 I: #6      _rootRun (dart:async/zone.dart:1122:38)
2020-01-09 21:27:36.998 I: #7      _CustomZone.run (dart:async/zone.dart:1023:19)
2020-01-09 21:27:36.998 I: #8      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
2020-01-09 21:27:36.998 I: #9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
2020-01-09 21:27:36.998 I: #10     _rootRun (dart:async/zone.dart:1126:13)
2020-01-09 21:27:36.998 I: #11     _CustomZone.run (dart:async/zone.dart:1023:19)
2020-01-09 21:27:36.998 I: #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
2020-01-09 21:27:36.998 I: #13     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
2020-01-09 21:27:36.998 I: #14     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
2020-01-09 21:27:36.998 I: #15     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
2020-01-09 21:27:36.998 I: #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

import 'dart:async';
import 'package:chainformation/database/dao/user_dao.dart';
import 'package:dio/dio.dart';
import 'package:dio/dio.dart' as dio;
import 'package:pretty_dio_logger/pretty_dio_logger.dart';

class HttpClient {
  UserDao userDao;
  Map<String, dynamic> headers;
  Dio httpClient;

  HttpClient({UserDao this.userDao}) {

  /*
    var _logInterceptor = PrettyDioLogger(
        requestHeader: true,
        requestBody: true,
        responseBody: true,
        responseHeader: false,
        compact: false,
        error: false);
*/
   var _logInterceptor=LogInterceptor(responseBody: true, requestBody: true);

    headers = {
      "Fic-App-Version": "4.0.0",
      "Accept": "application/json",
      "content-type": "application/json"
    };
    httpClient = Dio();
    httpClient.interceptors.add(_logInterceptor);
  }

  Future<Response> get(String url) async {
    if (userDao != null) {
      var user = await userDao.getLoginUser();
      if (user != null && user.tokenId != null) {
        String authToken = user.tokenId;
        headers["Authorization"] = "Basic " + authToken;
      }
    }

    var response = httpClient.get(url,
        options: dio.Options(
          headers: headers,
        ));
    return response;
  }
}

var _logInterceptor=LogInterceptor(responseBody: true, requestBody: true);
this workin good for me
 pretty_dio_logger: ^1.0.8

**Comment by Milad-Akarie** [comment]
Fixed in version 1.0.9
Thanks for reporting.
